version: '3.8'

services:
  local-database:
    image: postgres:14.4-alpine
    restart: unless-stopped
    container_name: local-database
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - local_data:/var/lib/postgresql/data

volumes:
  local_data:
    driver: local